on: [push]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Build and Upload
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the appropriate Node.js version
    - name: Install Dependencies
      run: npm install  # You might need to adjust this depending on your project
    - name: Build
      run: npm run build  # Replace with your build command
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.SERVER }}
        port: 22
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        localPath: './public'
        remotePath: './www'
